### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by chiayingc**

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
1. Who are you?
2. Paste live URLs for testing.

**Comment by chiayingc** [comment]
(陳佳瑩)
http://52.192.27.239:3000/api/attractions?page=1
http://52.192.27.239:3000/api/attractions?page=0&keyword=藝文館所
http://52.192.27.239:3000/api/attractions?page=0&keyword=北
http://52.192.27.239:3000/api/attraction/10

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. `images` field of attraction should be a string array where every image URL of attraction should be a element in this array. For example: `["Image URL 1", "Image URL 2", ...]`
2. Response format of http://52.192.27.239:3000/api/attraction/10 is incorrect.
3. http://52.192.27.239:3000/api/categories should be an array containing distinct attraction categories.

Solve these issues and re-request review.

**Comment by chiayingc** [comment]
(陳佳瑩)
http://52.192.27.239:3000/api/attractions?page=1
[http://52.192.27.239:3000/api/attractions?page=0&keyword=藝文館所
http://52.192.27.239:3000/api/categories
[http://52.192.27.239:3000/api/attractions?page=0&keyword=北
http://52.192.27.239:3000/api/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
1 and 2 are OK.

3. http://52.192.27.239:3000/api/categories should be an array containing DISTINCT attraction categories.

Resolve this issue and re-request review.

**Comment by chiayingc** [comment]
(陳佳瑩)


http://52.192.27.239:3000/api/categories
http://52.192.27.239:3000/api/attractions?page=0&keyword=北
http://52.192.27.239:3000/api/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going. :)

**Pull request merged**
